### ISSUE TITLE
iter_batched vs iter_batched_ref

### ISSUE THREAD

**Issue by Heinenen** [Voultapher/sort-research-rs#13] opened 2023-07-13 10:07 UTC
I tried coming up with why `cargo bench` and the `run_benchmarks.py` yielded different results for me. The option that made the difference was that the feature "cold_benchmarks" was enabled in the python script but not with `cargo bench`. This seemed odd to me as I was only executing the hot benchmarks. Do you know why this could be?

After replacing `iter_batched()` with `iter_batched_ref()` (see below), disabling or enabling the cold_benchmarks-feature didn't seem to make a difference anymore.

https://github.com/Voultapher/sort-research-rs/blob/91ae9c745642a259d4e33e0b6277db496bf9583d/benches/bench_other/util.rs#L97-L109
Is there a reason why you chose `iter_batched()` over `iter_batched_ref()`?
The main difference to me seems to be the timing model, `iter_batched()` additionaly accounts for the time it takes to drop the elements passed to it's `routine`. For small test sizes this seems to matter substantially.

**Comment by Voultapher** [comment] 2023-07-21 14:59
Sorry for the late reply, I was on vacation.

Let me unpack this.

- Do I understand correctly, you get different results for the same hot benchmark depending if the feature `"cold_benchmarks"` is enabled or not? I can't reproduce this effect on my machine. One of my go-to combination is hot-u64-random-10000, maybe it shows up somewhere else. But the code is isolated, the only differences should be code layout and allocation placements, which can have a significant effects, but are out of my control.

- Why is it disabled by default? All but the basic implementations and benchmarks are enabled by default. Everything else is behind feature gates. This is to save on compile times, and allow for faster iterations, as well as some features are not compatible across ISAs and OSs.

- Why does the benchmark script enable the feature `"cold_benchmarks"`, that's because I regularly use it to collect benchmarks results for many inputs combinations, which is a different workflow for to me than iteratively working on some experiment.

- Why `iter_batched()` and not `iter_batched_ref()`? I didn't know `iter_batched_ref()` was a thing. Can you please elaborate what you mean by "The main difference to me seems to be the timing model". Looking at it, it seems `iter_batched_ref()` is a better fit for my benchmarks. Thanks for the suggestion! Looking at the results for example `rust_ipnsort_unstable-cold-u64-random-8` goes from 119ns -> 111ns and rust_ipnsort_unstable-hot-u64-random-8 goes from 45ns -> 39ns. This suggests that there was a constant overhead in both cases, which could be explained by the cost of dropping a `Vec`.

Please let me know if that addresses your questions.

**Comment by Heinenen** [comment] 2023-07-23 12:27
I hope you had a nice vacation! Thanks for taking the time to answer.

> Do I understand correctly, you get different results for the same hot benchmark depending if the feature "cold_benchmarks" is enabled or not?

Yes. For my algorithm which is not (yet) contained in the suite I had bigger differences in results but for simpliciity's sake I just ran `rust_std_unstable` and got similar results (my algorithm uses the same insertion sort as std-sort anyways). See the image below for the results, the exact command used is `CUSTOM_BENCH_REGEX="(rust_std_unstable-).*hot.*i32.*(-random-).*(1|2|3|4|6|8|10|12|17|24|35|49|70|100|200)\$" python util/run_benchmarks.py cold_disabled_ryzen`

![image](https://github.com/Voultapher/sort-research-rs/assets/37484430/68e929e6-8685-4ffb-a311-5ee8887fbc9f)

> Can you please elaborate what you mean by "The main difference to me seems to be the timing model".

I didn't look at the code of the two functions but the documentation of both is exactly the same except for the section "Timing model", which is stated as
* `elapsed = (Instant::now * num_batches) + (iters * (routine + O::drop)) + Vec::extend`
* `elapsed = (Instant::now * num_batches) + (iters *  routine)            + Vec::extend`

for `iter_batched()` and `iter_batched_ref()` respectively.

**Comment by Voultapher** [comment] 2023-07-29 08:06
> Yes. For my algorithm which is not (yet) contained in the suite I had bigger differences in results [...]

Oh interesting, thanks for sharing. I've since switched to `iter_batched_ref` so that should no longer be an issue right? Do you mind sharing the context of your algorithm? Because a word of caution, using hot benchmarks for these small sizes has little predictive power and can be misleading, I talked more about it here https://github.com/Voultapher/sort-research-rs/blob/main/writeup/intel_avx512/text.md.

> I didn't look at the code of the two functions but the documentation of both is exactly the same except for the section "Timing model", which is stated as

Ah I missed that part in the documentation.

**Comment by Heinenen** [comment] 2023-07-29 09:13
Its' basically a Rust re-implementation of ips4o and I'm doing some tweaks to make it more adaptive to nearly sorted inputs. I don't think I will be optimizing for small cases that much anyways and just use a copy-pasted version of rust_std's insertion sort. I was just wondering why Rust's insertion sort was quite a bit slower than the variant used in C++ ips4o, that's why I started investigating.

I am currently writing my bachelor thesis about it so I will probably share the results and the code in a couple of weeks when I'm done.

**Comment by Voultapher** [comment] 2023-07-29 09:28
Interesting, ips4o was the least "safe" generic implementation I've come across. Failing all panic, observation and ord safety tests. Are you addressing these issues in your port?

**Comment by Heinenen** [comment] 2023-07-29 09:44
No, not really. The panic safety aspect is probably relatively straightforward to get right, as we have to keep track where the empty spots in the input are either way.
For observable comparisons one would probably have to do some stuff with the classifier to copy them back into the input.
I don't yet have an intuition on what would do with a broken ordering.

**Comment by Voultapher** [comment] 2023-07-29 10:19
Sounds good, make sure to mark the `sort` interface as `unsafe` because any of the above issues results in an unsafe interface per Rust semantics.

I'm closing the issue now, the original question was addressed.

**Closed by Voultapher** 2023-07-29 10:19 UTC
